name: Build and Test

on: push

jobs:
  # https://github.com/marketplace/actions/github-action-for-yarn
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: prod
      - uses: borales/actions-yarn@v2.0.0
        env:
          CI: true
        with:
          cmd: test
