---
- hosts: somethingmore
  vars_prompt:
    - name: git_branch
      prompt: Please type git branch
      private: no
  tasks:
    - name: test connection
      ping:
    - name: git checkout
      git:
        repo: git@github.com:job-scrapper/frontend.git
        dest: /home/some/job-scrapper/frontend
        version: "{{ git_branch }}"
      register: output_commits
    - name: Display commit info
      debug:
        var: output_commits
    - name: Write dotenv
      shell: |
        echo 'GENERATE_SOURCEMAP=false
        INLINE_RUNTIME_CHUNK=false' >> /home/some/job-scrapper/frontend/.env
    - name: build new image
      become: true
      docker_image:
        name: job-frontend
        tag: "{{ output_commits.after[:7] }}"
        build:
          path: /home/some/job-scrapper/frontend
        source: build
    - name: Remove old container
      become: true
      docker_container:
        name: "{{ output_commits.before[:7] }}"
        state: absent
    - name: Run new container
      become: true
      docker_container:
        name: "{{ output_commits.after[:7] }}"
        image: "job-frontend:{{ output_commits.after[:7] }}"
        ports: "3030:3030"
    - name: Restart nginx
      become: true
      service:
        name: nginx
        state: restarted
    - name: Remove old image
      become: true
      ignore_errors: yes
      docker_image:
        name: job-frontend
        tag: "{{ output_commits.after[:7] }}"
        state: absent
    - name: prune dangling images
      become: true
      docker_prune:
        images: yes
        images_filters:
          dangling: true
